### ISSUE TITLE
UndefVarError on Two Chapters

### ISSUE THREAD

**Issue by tegedik** [storopoli/Bayesian-Julia#83]
Hello, 

There are `UndefVarError` errors in two chapters (7 & 8) on logistic regression, (e.g., `UndefVarError: chain not defined` in [here](https://storopoli.io/Bayesian-Julia/pages/07_logistic_reg/)). Btw. the codes run without problem on my machine. 

Thanks for this tutorial.

**Comment by storopoli** [comment]
#84 should fix this.
Please check again once this PR is merged and the website re-rendered in CI.

**Comment by storopoli** [comment]
Is is live and fixed.

**Comment by tegedik** [comment]
Thank you.

**Comment by tegedik** [comment]
Thank you. Unfortunately, errors on Chapter 8 were not fixed.

**Comment by storopoli** [comment]
Ok Chapter 8 (Bayesian ordinal regression) is fixed.
